# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kaguya.v1 import kaguya_pb2 as kaguya_dot_v1_dot_kaguya__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kaguya/v1/kaguya_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ListenerServiceStub(object):
    """LISTENER SERVICE — Bidi streaming
    Gateway = client, Listener = server

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/kaguya.v1.ListenerService/Stream',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.ListenerInput.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.ListenerOutput.FromString,
                _registered_method=True)


class ListenerServiceServicer(object):
    """LISTENER SERVICE — Bidi streaming
    Gateway = client, Listener = server

    """

    def Stream(self, request_iterator, context):
        """Bidi: Gateway pushes audio chunks, Listener pushes back ASR events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListenerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.ListenerInput.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.ListenerOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.ListenerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.ListenerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListenerService(object):
    """LISTENER SERVICE — Bidi streaming
    Gateway = client, Listener = server

    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kaguya.v1.ListenerService/Stream',
            kaguya_dot_v1_dot_kaguya__pb2.ListenerInput.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.ListenerOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TalkerServiceStub(object):
    """TALKER SERVICE — Bidi ProcessPrompt + unary helpers
    Gateway = client, Talker = server

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Converse = channel.stream_stream(
                '/kaguya.v1.TalkerService/Converse',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.TalkerInput.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.TalkerOutput.FromString,
                _registered_method=True)
        self.PrefillCache = channel.unary_unary(
                '/kaguya.v1.TalkerService/PrefillCache',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.PrefillRequest.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.PrefillAck.FromString,
                _registered_method=True)
        self.UpdatePersona = channel.unary_unary(
                '/kaguya.v1.TalkerService/UpdatePersona',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.PersonaConfig.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.PersonaAck.FromString,
                _registered_method=True)


class TalkerServiceServicer(object):
    """TALKER SERVICE — Bidi ProcessPrompt + unary helpers
    Gateway = client, Talker = server

    """

    def Converse(self, request_iterator, context):
        """Bidi: Gateway sends context + inline barge-in; Talker streams output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrefillCache(self, request, context):
        """Between-turn operations (unary, no need for bidi)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePersona(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TalkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Converse': grpc.stream_stream_rpc_method_handler(
                    servicer.Converse,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.TalkerInput.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.TalkerOutput.SerializeToString,
            ),
            'PrefillCache': grpc.unary_unary_rpc_method_handler(
                    servicer.PrefillCache,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.PrefillRequest.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.PrefillAck.SerializeToString,
            ),
            'UpdatePersona': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePersona,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.PersonaConfig.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.PersonaAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.TalkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.TalkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TalkerService(object):
    """TALKER SERVICE — Bidi ProcessPrompt + unary helpers
    Gateway = client, Talker = server

    """

    @staticmethod
    def Converse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kaguya.v1.TalkerService/Converse',
            kaguya_dot_v1_dot_kaguya__pb2.TalkerInput.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.TalkerOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrefillCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.TalkerService/PrefillCache',
            kaguya_dot_v1_dot_kaguya__pb2.PrefillRequest.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.PrefillAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.TalkerService/UpdatePersona',
            kaguya_dot_v1_dot_kaguya__pb2.PersonaConfig.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.PersonaAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReasonerServiceStub(object):
    """REASONER SERVICE — Multi-stream design

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Delegate = channel.stream_stream(
                '/kaguya.v1.ReasonerService/Delegate',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.DelegateInput.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.DelegateOutput.FromString,
                _registered_method=True)
        self.Interrupt = channel.unary_unary(
                '/kaguya.v1.ReasonerService/Interrupt',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.InterruptRequest.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.InterruptAck.FromString,
                _registered_method=True)
        self.Telemetry = channel.unary_stream(
                '/kaguya.v1.ReasonerService/Telemetry',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.TelemetrySubscribe.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.TelemetryEvent.FromString,
                _registered_method=True)


class ReasonerServiceServicer(object):
    """REASONER SERVICE — Multi-stream design

    """

    def Delegate(self, request_iterator, context):
        """Bidi per-task: Gateway sends task + context updates, Reasoner streams events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interrupt(self, request, context):
        """Unary interrupt: always available, even when no delegation in flight
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Telemetry(self, request, context):
        """Server-streaming telemetry: continuous background context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReasonerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Delegate': grpc.stream_stream_rpc_method_handler(
                    servicer.Delegate,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.DelegateInput.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.DelegateOutput.SerializeToString,
            ),
            'Interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.Interrupt,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.InterruptRequest.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.InterruptAck.SerializeToString,
            ),
            'Telemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.Telemetry,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.TelemetrySubscribe.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.TelemetryEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.ReasonerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.ReasonerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReasonerService(object):
    """REASONER SERVICE — Multi-stream design

    """

    @staticmethod
    def Delegate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kaguya.v1.ReasonerService/Delegate',
            kaguya_dot_v1_dot_kaguya__pb2.DelegateInput.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.DelegateOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.ReasonerService/Interrupt',
            kaguya_dot_v1_dot_kaguya__pb2.InterruptRequest.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.InterruptAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Telemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kaguya.v1.ReasonerService/Telemetry',
            kaguya_dot_v1_dot_kaguya__pb2.TelemetrySubscribe.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.TelemetryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RouterControlServiceStub(object):
    """─────────────────────────────────────────────
    GATEWAY CONTROL (Endpoint → Gateway)
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendControl = channel.unary_unary(
                '/kaguya.v1.RouterControlService/SendControl',
                request_serializer=kaguya_dot_v1_dot_kaguya__pb2.ControlSignal.SerializeToString,
                response_deserializer=kaguya_dot_v1_dot_kaguya__pb2.ControlAck.FromString,
                _registered_method=True)


class RouterControlServiceServicer(object):
    """─────────────────────────────────────────────
    GATEWAY CONTROL (Endpoint → Gateway)
    ─────────────────────────────────────────────

    """

    def SendControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControl,
                    request_deserializer=kaguya_dot_v1_dot_kaguya__pb2.ControlSignal.FromString,
                    response_serializer=kaguya_dot_v1_dot_kaguya__pb2.ControlAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.RouterControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.RouterControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterControlService(object):
    """─────────────────────────────────────────────
    GATEWAY CONTROL (Endpoint → Gateway)
    ─────────────────────────────────────────────

    """

    @staticmethod
    def SendControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.RouterControlService/SendControl',
            kaguya_dot_v1_dot_kaguya__pb2.ControlSignal.SerializeToString,
            kaguya_dot_v1_dot_kaguya__pb2.ControlAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
