"""voice/listener.py — RealtimeSTT wrapper + ListenerService gRPC client → Gateway.

Domain role: Captures speech, detects turns (via turn_detection.py), streams
ListenerEvents to the Gateway.

gRPC role: CLIENT — dials Gateway's ListenerService, streams ListenerEvent messages.
The gRPC client is embedded here (not a standalone client.py) because it is
tightly coupled to listener logic and not shared by other components. See §8 IPC note.
"""

import asyncio
import logging
import time
import grpc
from RealtimeSTT import AudioToTextRecorder

from config import TalkerConfig
from voice.opus_decoder import OpusDecoder
from voice.turn_detection import TurnDetector

# Proto stubs — committed to repo (regenerate with `make proto` if schema changes).
# Generated by grpcio-tools, patched for relative imports. See REF-005.
from proto import kaguya_pb2, kaguya_pb2_grpc  # type: ignore[import]

logger = logging.getLogger(__name__)


class Listener:
    """Wraps RealtimeSTT and streams ListenerEvents to the Gateway.

    Lifecycle:
        listener = Listener(config)
        await listener.run()  # blocks; cancelled on shutdown
    """

    def __init__(self, config: TalkerConfig) -> None:
        self._config = config
        self._opus = OpusDecoder()
        self._turn_detector = TurnDetector(config)
        self._event_queue: asyncio.Queue[kaguya_pb2.ListenerEvent] = asyncio.Queue()
        self._recorder: AudioToTextRecorder | None = None
        self._loop: asyncio.AbstractEventLoop | None = None

    # ──────────────────────────────────────────
    # Public entry point
    # ──────────────────────────────────────────

    async def run(self) -> None:
        """Start the listener loop and gRPC stream concurrently."""
        self._loop = asyncio.get_running_loop()
        recorder_task = asyncio.create_task(self._run_recorder())
        stream_task = asyncio.create_task(self._stream_to_gateway())
        try:
            await asyncio.gather(recorder_task, stream_task)
        except asyncio.CancelledError:
            recorder_task.cancel()
            stream_task.cancel()
            raise

    def feed_opus(self, opus_frame: bytes) -> None:
        """Feed one Opus audio frame from the Gateway WebSocket.

        Called by the WebSocket demux in the dev-GUI/TUI endpoint (Phase 1).
        Decodes to PCM and forwards to RealtimeSTT.
        """
        if self._recorder is None:
            return
        pcm = self._opus.decode(opus_frame)
        self._recorder.feed_audio(pcm)

    # ──────────────────────────────────────────
    # RealtimeSTT recorder (runs via asyncio.to_thread)
    # ──────────────────────────────────────────

    async def _run_recorder(self) -> None:
        """Start RealtimeSTT in a background thread (it uses blocking callbacks)."""
        await asyncio.to_thread(self._recorder_thread)

    def _recorder_thread(self) -> None:
        recorder = AudioToTextRecorder(
            model="distil-large-v3",
            compute_type="int8",
            language="en",
            use_microphone=False,  # we push audio via feed_audio()
            on_vad_detect_start=self._on_vad_start,
            on_vad_detect_stop=self._on_vad_stop,
            on_realtime_transcription_update=self._on_partial,
        )
        self._recorder = recorder
        # RealtimeSTT's own transcription_complete fires on VAD silence — we do NOT
        # use it as final_transcript. Turn detection in turn_detection.py decides when
        # to emit final_transcript. Pass partial updates there instead.
        recorder.start()  # blocks until stop() is called

    # ──────────────────────────────────────────
    # RealtimeSTT callbacks (called from recorder thread)
    # ──────────────────────────────────────────

    def _on_vad_start(self) -> None:
        self._turn_detector.on_speech_start()
        event = kaguya_pb2.ListenerEvent(
            timestamp_ms=_now_ms(),
            vad_speech_start=kaguya_pb2.VadSpeechStart(),
        )
        self._event_queue.put_nowait(event)

    def _on_vad_stop(self, silence_duration_ms: float) -> None:
        self._turn_detector.on_vad_stop()
        event = kaguya_pb2.ListenerEvent(
            timestamp_ms=_now_ms(),
            vad_speech_end=kaguya_pb2.VadSpeechEnd(
                silence_duration_ms=silence_duration_ms
            ),
        )
        self._event_queue.put_nowait(event)
        # Kick off the silence tick loop to handle the unconditional 800ms emit.
        if self._loop is not None:
            asyncio.run_coroutine_threadsafe(self._silence_tick_loop(), self._loop)

    def _on_partial(self, text: str) -> None:
        event = kaguya_pb2.ListenerEvent(
            timestamp_ms=_now_ms(),
            partial_transcript=kaguya_pb2.PartialTranscript(text=text),
        )
        self._event_queue.put_nowait(event)
        # Also hand to turn detector so it can evaluate syntactic completeness.
        final = self._turn_detector.on_partial(text)
        if final is not None:
            self._emit_final(final)

    async def _silence_tick_loop(self) -> None:
        """Poll the turn detector every 100ms while in silence.

        Handles the unconditional 800ms emit for the case where partial updates
        have stopped but the threshold hasn't been reached via on_partial alone.
        """
        while True:
            await asyncio.sleep(0.1)
            final = self._turn_detector.on_silence_tick()
            if final is not None:
                self._emit_final(final)
                return
            # If the turn detector has already emitted, we can stop ticking.
            if self._turn_detector.has_emitted:
                return

    def _emit_final(self, text: str) -> None:
        event = kaguya_pb2.ListenerEvent(
            timestamp_ms=_now_ms(),
            final_transcript=kaguya_pb2.FinalTranscript(text=text, confidence=1.0),
        )
        self._event_queue.put_nowait(event)

    # ──────────────────────────────────────────
    # gRPC client — ListenerService → Gateway
    # ──────────────────────────────────────────

    async def _stream_to_gateway(self) -> None:
        """Connect to Gateway's ListenerService and stream events.

        Reconnects with exponential backoff on connection loss.
        """
        backoff = 1.0
        socket_addr = f"unix://{self._config.gateway_socket}"

        while True:
            try:
                async with grpc.aio.insecure_channel(socket_addr) as channel:
                    stub = kaguya_pb2_grpc.ListenerServiceStub(channel)
                    await stub.StreamEvents(self._event_generator())
                    backoff = 1.0
            except grpc.aio.AioRpcError as exc:
                logger.warning(
                    "Gateway connection lost (%s). Reconnecting in %.1fs...",
                    exc.code(),
                    backoff,
                )
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 30.0)
            except asyncio.CancelledError:
                return

    async def _event_generator(self):
        """Async generator that yields queued ListenerEvents to the gRPC stream."""
        while True:
            event = await self._event_queue.get()
            yield event


def _now_ms() -> int:
    return int(time.time() * 1000)
