"""voice/listener.py — RealtimeSTT wrapper + ListenerService gRPC client → Gateway.

Domain role: Captures speech, detects turns (via turn_detector.py), streams
ListenerEvents to the Gateway.

gRPC role: CLIENT — dials Gateway's ListenerService, streams ListenerEvent messages.
The gRPC client is embedded here (not a standalone client.py) because it is
tightly coupled to listener logic and not shared by other components. See §8 IPC note.
"""

import asyncio
import logging
import time

import grpc
from RealtimeSTT import AudioToTextRecorder

from config import TalkerConfig
from voice.opus_decoder import OpusDecoder
from voice.turn_detector import TurnDetector

# Proto stubs — committed to repo (regenerate with `make proto` if schema changes).
# Generated by grpcio-tools, patched for relative imports. See REF-005.
from proto import kaguya_pb2, kaguya_pb2_grpc  # type: ignore[import]

logger = logging.getLogger(__name__)


def _gateway_target_for_temp_tcp(raw: str) -> str:
    """Temporary Windows-safe routing: divert unix-style targets to TCP."""
    value = raw.strip()
    if "://" in value and not value.startswith(("http://", "https://", "dns://")):
        logger.warning(
            "Temporary TCP fallback: ignoring non-TCP gateway target '%s', using 127.0.0.1:50051",
            value,
        )
        return "127.0.0.1:50051"

    # Path-like values are treated as unix sockets in this codebase; divert for now.
    if "/" in value or "\\" in value:
        logger.warning(
            "Temporary TCP fallback: ignoring path-like gateway target '%s', using 127.0.0.1:50051",
            value,
        )
        return "127.0.0.1:50051"

    # host:port remains untouched.
    return value


class Listener:
    """Wraps RealtimeSTT and streams ListenerEvents to the Gateway.

    Lifecycle:
        listener = Listener(config)
        await listener.run()  # blocks; cancelled on shutdown
    """

    def __init__(self, config: TalkerConfig) -> None:
        self._config = config
        self._opus = OpusDecoder()
        self._turn_detector = TurnDetector(config)
        self._event_queue: asyncio.Queue[kaguya_pb2.ListenerEvent] = asyncio.Queue()
        self._recorder: AudioToTextRecorder | None = None
        self._loop: asyncio.AbstractEventLoop | None = None

    # ──────────────────────────────────────────
    # Public entry point
    # ──────────────────────────────────────────

    async def run(self) -> None:
        """Start the listener loop and gRPC stream concurrently."""
        self._loop = asyncio.get_running_loop()
        recorder_task = asyncio.create_task(self._run_recorder())
        stream_task = asyncio.create_task(self._stream_to_gateway())
        try:
            await asyncio.gather(recorder_task, stream_task)
        except asyncio.CancelledError:
            recorder_task.cancel()
            stream_task.cancel()
            # Clean shutdown: stop RealtimeSTT from a non-recorder thread.
            # shutdown() is thread-safe, idempotent, and unblocks start().
            if self._recorder is not None:
                self._recorder.shutdown()
            raise

    def feed_opus(self, opus_frame: bytes) -> None:
        """Feed one Opus audio frame from the Gateway.

        TODO: Nothing calls this yet. Needs a raw Unix socket reader task in
        main.py or a dev-mode microphone capture task for local testing.
        See implementation plan for audio input plumbing.

        Decodes to PCM and forwards to RealtimeSTT.
        """
        if self._recorder is None:
            return
        pcm = self._opus.decode(opus_frame)
        if pcm:
            self._recorder.feed_audio(pcm)

    # ──────────────────────────────────────────
    # RealtimeSTT recorder (runs via asyncio.to_thread)
    # ──────────────────────────────────────────

    async def _run_recorder(self) -> None:
        """Start RealtimeSTT in a background thread (it uses blocking callbacks)."""
        await asyncio.to_thread(self._recorder_thread)

    def _recorder_thread(self) -> None:
        recorder = AudioToTextRecorder(
            model=self._config.whisper_model,
            compute_type=self._config.whisper_compute_type,
            language=self._config.whisper_language,
            use_microphone=False,  # we push audio via feed_audio()
            on_vad_detect_start=self._on_vad_start,
            on_vad_detect_stop=self._on_vad_stop,
            on_realtime_transcription_update=self._on_partial,
        )
        self._recorder = recorder
        # RealtimeSTT's own transcription_complete fires on VAD silence — we do NOT
        # use it as final_transcript. Our turn_detector.py has a two-tier
        # (300ms syntax-aware + 800ms unconditional) design that is more appropriate
        # for conversational turn-taking than RealtimeSTT's single-threshold approach.
        # We use RealtimeSTT only for Whisper inference and VAD callbacks.
        recorder.start()  # blocks until shutdown() is called

    # ──────────────────────────────────────────
    # RealtimeSTT callbacks (called from recorder thread)
    # ──────────────────────────────────────────
    # IMPORTANT: These run on the recorder thread, not the asyncio event loop.
    # asyncio.Queue is not thread-safe (see REF-007). We use
    # loop.call_soon_threadsafe() to safely enqueue events from this thread.

    def _enqueue(self, event: kaguya_pb2.ListenerEvent) -> None:
        """Thread-safe enqueue of a ListenerEvent onto the async event queue."""
        if self._loop is not None:
            self._loop.call_soon_threadsafe(self._event_queue.put_nowait, event)

    def _on_vad_start(self) -> None:
        self._turn_detector.on_speech_start()
        self._enqueue(
            kaguya_pb2.ListenerEvent(
                timestamp_ms=_now_ms(),
                vad_speech_start=kaguya_pb2.VadSpeechStart(),
            )
        )

    def _on_vad_stop(self, silence_duration_ms: float) -> None:
        self._turn_detector.on_vad_stop()
        self._enqueue(
            kaguya_pb2.ListenerEvent(
                timestamp_ms=_now_ms(),
                vad_speech_end=kaguya_pb2.VadSpeechEnd(
                    silence_duration_ms=silence_duration_ms
                ),
            )
        )
        # Kick off the silence tick loop to handle the unconditional 800ms emit.
        # Pass turn_id so the loop can detect if a new utterance has started
        # (which would make this tick loop stale — it should exit).
        if self._loop is not None:
            turn_id = self._turn_detector.turn_id
            asyncio.run_coroutine_threadsafe(
                self._silence_tick_loop(turn_id), self._loop
            )

    def _on_partial(self, text: str) -> None:
        self._enqueue(
            kaguya_pb2.ListenerEvent(
                timestamp_ms=_now_ms(),
                partial_transcript=kaguya_pb2.PartialTranscript(text=text),
            )
        )
        # Also hand to turn detector so it can evaluate syntactic completeness.
        final = self._turn_detector.on_partial(text)
        if final is not None:
            self._emit_final(final)

    async def _silence_tick_loop(self, started_turn_id: int) -> None:
        """Poll the turn detector while in silence.

        Handles the unconditional 800ms emit for the case where partial updates
        have stopped but the threshold hasn't been reached via on_partial alone.

        Args:
            started_turn_id: The turn_id when this loop was launched. If the
                turn detector's turn_id has changed, a new utterance has started
                and this loop is stale — exit immediately.
        """
        tick_s = self._config.silence_tick_interval_ms / 1000.0
        while True:
            await asyncio.sleep(tick_s)
            # Stale loop check: a new utterance has started since we launched.
            if self._turn_detector.turn_id != started_turn_id:
                return
            final = self._turn_detector.on_silence_tick()
            if final is not None:
                self._emit_final(final)
                return
            # If the turn detector has already emitted, we can stop ticking.
            if self._turn_detector.has_emitted:
                return

    def _emit_final(self, text: str) -> None:
        # confidence=0.0: RealtimeSTT does not expose per-transcript confidence
        # scores in its callback API. 0.0 signals "unknown" to downstream consumers.
        # TODO: Propagate Whisper's per-segment log-probabilities when available.
        self._enqueue(
            kaguya_pb2.ListenerEvent(
                timestamp_ms=_now_ms(),
                final_transcript=kaguya_pb2.FinalTranscript(text=text, confidence=0.0),
            )
        )

    # ──────────────────────────────────────────
    # gRPC client — ListenerService → Gateway
    # ──────────────────────────────────────────

    async def _stream_to_gateway(self) -> None:
        """Connect to Gateway's ListenerService and stream events.

        Reconnects with exponential backoff on connection loss.
        """
        backoff = self._config.gateway_reconnect_initial_s
        socket_addr = _gateway_target_for_temp_tcp(self._config.gateway_socket)

        while True:
            try:
                async with grpc.aio.insecure_channel(socket_addr) as channel:
                    stub = kaguya_pb2_grpc.ListenerServiceStub(channel)
                    await stub.StreamEvents(self._event_generator())
                    backoff = self._config.gateway_reconnect_initial_s
            except grpc.aio.AioRpcError as exc:
                logger.warning(
                    "Gateway connection lost (%s). Reconnecting in %.1fs...",
                    exc.code(),
                    backoff,
                )
                await asyncio.sleep(backoff)
                backoff = min(
                    backoff * self._config.gateway_reconnect_multiplier,
                    self._config.gateway_reconnect_max_s,
                )
            except asyncio.CancelledError:
                return

    async def _event_generator(self):
        """Async generator that yields queued ListenerEvents to the gRPC stream."""
        while True:
            event = await self._event_queue.get()
            yield event


def _now_ms() -> int:
    return int(time.time() * 1000)
