#!/usr/bin/env python3
"""Generate Python proto stubs and patch imports to use relative imports.

Usage:
  From repo root:   make proto
  From talker/:     python scripts/gen_proto.py

This script is only needed when the proto schema changes. End users can use
the committed stubs directly without regeneration.
"""

import subprocess
import sys
from pathlib import Path


def main():
    repo_root = Path(__file__).parent.parent.parent
    talker_dir = repo_root / "talker"
    proto_dir = talker_dir / "proto"
    proto_src = repo_root / "proto" / "kaguya" / "v1" / "kaguya.proto"

    # Ensure output directory exists
    proto_dir.mkdir(exist_ok=True)

    # Generate stubs using grpcio-tools (bundled protoc)
    print("==> Generating Python stubs with grpcio-tools...")
    subprocess.run(
        [
            sys.executable,
            "-m",
            "grpc_tools.protoc",
            f"-I{proto_src.parent}",
            f"--python_out={proto_dir}",
            f"--grpc_python_out={proto_dir}",
            proto_src.name,
        ],
        check=True,
        cwd=talker_dir,
    )

    # Patch grpc file to use relative import
    grpc_file = proto_dir / "kaguya_pb2_grpc.py"
    if grpc_file.exists():
        content = grpc_file.read_text(encoding="utf-8")
        patched = content.replace(
            "import kaguya_pb2 as kaguya__pb2",
            "from . import kaguya_pb2 as kaguya__pb2",
        )
        grpc_file.write_text(patched, encoding="utf-8")
        print(f"    Patched: {grpc_file.relative_to(repo_root)}")

    # Create __init__.py
    init_file = proto_dir / "__init__.py"
    init_file.write_text(
        '''"""Generated gRPC stubs for kaguya.v1.

Generated by: scripts/gen_proto.py (via grpcio-tools)
Source: proto/kaguya/v1/kaguya.proto

Re-generate with: make proto (from repo root)
"""

__all__ = ["kaguya_pb2", "kaguya_pb2_grpc"]
''',
        encoding="utf-8",
    )
    print(f"    Created: {init_file.relative_to(repo_root)}")

    print("==> Done. Commit the generated files:")
    print(f"    git add {proto_dir.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
