"""Generated gRPC stubs for kaguya.v1.

Generated by: scripts/gen_proto.py (via grpcio-tools)
Source: proto/kaguya/v1/kaguya.proto

Re-generate with: make proto (from repo root)
"""

__all__ = ["kaguya_pb2", "kaguya_pb2_grpc"]
