"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import kaguya_pb2 as _kaguya_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ListenerServiceStub:
    """LISTENER SERVICE — Bidi streaming
    Gateway = client, Listener = server

    Audio bytes do NOT flow over this gRPC stream. The Gateway forwards raw
    audio frames over a separate TCP socket (length-prefixed framing) at
    `listener_audio_addr`. Reasoning: 50fps audio + protobuf serialization
    overhead is wasteful for the Phase-1 local-only deployment, and gRPC's
    HTTP/2 framing adds head-of-line blocking that voice latency can't
    afford. See `docs/spec-agent-v0.1.0.md` and the raw-socket forwarder in
    `gateway/src/listener.rs`.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ListenerServiceAsyncStub: ...
    Stream: _grpc.StreamStreamMultiCallable[_kaguya_pb2.ListenerInput, _kaguya_pb2.ListenerOutput]
    """Bidi: Gateway sends control signals; Listener streams ASR events."""

@_typing.type_check_only
class ListenerServiceAsyncStub(ListenerServiceStub):
    """LISTENER SERVICE — Bidi streaming
    Gateway = client, Listener = server

    Audio bytes do NOT flow over this gRPC stream. The Gateway forwards raw
    audio frames over a separate TCP socket (length-prefixed framing) at
    `listener_audio_addr`. Reasoning: 50fps audio + protobuf serialization
    overhead is wasteful for the Phase-1 local-only deployment, and gRPC's
    HTTP/2 framing adds head-of-line blocking that voice latency can't
    afford. See `docs/spec-agent-v0.1.0.md` and the raw-socket forwarder in
    `gateway/src/listener.rs`.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Stream: _aio.StreamStreamMultiCallable[_kaguya_pb2.ListenerInput, _kaguya_pb2.ListenerOutput]  # type: ignore[assignment]
    """Bidi: Gateway sends control signals; Listener streams ASR events."""

class ListenerServiceServicer(metaclass=_abc_1.ABCMeta):
    """LISTENER SERVICE — Bidi streaming
    Gateway = client, Listener = server

    Audio bytes do NOT flow over this gRPC stream. The Gateway forwards raw
    audio frames over a separate TCP socket (length-prefixed framing) at
    `listener_audio_addr`. Reasoning: 50fps audio + protobuf serialization
    overhead is wasteful for the Phase-1 local-only deployment, and gRPC's
    HTTP/2 framing adds head-of-line blocking that voice latency can't
    afford. See `docs/spec-agent-v0.1.0.md` and the raw-socket forwarder in
    `gateway/src/listener.rs`.
    """

    @_abc_1.abstractmethod
    def Stream(
        self,
        request_iterator: _MaybeAsyncIterator[_kaguya_pb2.ListenerInput],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_kaguya_pb2.ListenerOutput], _abc.AsyncIterator[_kaguya_pb2.ListenerOutput]]:
        """Bidi: Gateway sends control signals; Listener streams ASR events."""

def add_ListenerServiceServicer_to_server(servicer: ListenerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class TalkerServiceStub:
    """TALKER SERVICE — Bidi ProcessPrompt + unary helpers
    Gateway = client, Talker = server
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TalkerServiceAsyncStub: ...
    Converse: _grpc.StreamStreamMultiCallable[_kaguya_pb2.TalkerInput, _kaguya_pb2.TalkerOutput]
    """Bidi: Gateway sends context + inline barge-in; Talker streams output"""
    PrefillCache: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.PrefillRequest, _kaguya_pb2.PrefillAck]
    """Between-turn operations (unary, no need for bidi)"""
    UpdatePersona: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.PersonaConfig, _kaguya_pb2.PersonaAck]

@_typing.type_check_only
class TalkerServiceAsyncStub(TalkerServiceStub):
    """TALKER SERVICE — Bidi ProcessPrompt + unary helpers
    Gateway = client, Talker = server
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Converse: _aio.StreamStreamMultiCallable[_kaguya_pb2.TalkerInput, _kaguya_pb2.TalkerOutput]  # type: ignore[assignment]
    """Bidi: Gateway sends context + inline barge-in; Talker streams output"""
    PrefillCache: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.PrefillRequest, _kaguya_pb2.PrefillAck]  # type: ignore[assignment]
    """Between-turn operations (unary, no need for bidi)"""
    UpdatePersona: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.PersonaConfig, _kaguya_pb2.PersonaAck]  # type: ignore[assignment]

class TalkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """TALKER SERVICE — Bidi ProcessPrompt + unary helpers
    Gateway = client, Talker = server
    """

    @_abc_1.abstractmethod
    def Converse(
        self,
        request_iterator: _MaybeAsyncIterator[_kaguya_pb2.TalkerInput],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_kaguya_pb2.TalkerOutput], _abc.AsyncIterator[_kaguya_pb2.TalkerOutput]]:
        """Bidi: Gateway sends context + inline barge-in; Talker streams output"""

    @_abc_1.abstractmethod
    def PrefillCache(
        self,
        request: _kaguya_pb2.PrefillRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.PrefillAck, _abc.Awaitable[_kaguya_pb2.PrefillAck]]:
        """Between-turn operations (unary, no need for bidi)"""

    @_abc_1.abstractmethod
    def UpdatePersona(
        self,
        request: _kaguya_pb2.PersonaConfig,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.PersonaAck, _abc.Awaitable[_kaguya_pb2.PersonaAck]]: ...

def add_TalkerServiceServicer_to_server(servicer: TalkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class ReasonerServiceStub:
    """REASONER SERVICE — Multi-stream design"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ReasonerServiceAsyncStub: ...
    Delegate: _grpc.StreamStreamMultiCallable[_kaguya_pb2.DelegateInput, _kaguya_pb2.DelegateOutput]
    """Bidi per-task: Gateway sends task + context updates, Reasoner streams events"""
    Interrupt: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.InterruptRequest, _kaguya_pb2.InterruptAck]
    """Unary interrupt: always available, even when no delegation in flight"""
    Telemetry: _grpc.UnaryStreamMultiCallable[_kaguya_pb2.TelemetrySubscribe, _kaguya_pb2.TelemetryEvent]
    """Server-streaming telemetry: continuous background context"""

@_typing.type_check_only
class ReasonerServiceAsyncStub(ReasonerServiceStub):
    """REASONER SERVICE — Multi-stream design"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Delegate: _aio.StreamStreamMultiCallable[_kaguya_pb2.DelegateInput, _kaguya_pb2.DelegateOutput]  # type: ignore[assignment]
    """Bidi per-task: Gateway sends task + context updates, Reasoner streams events"""
    Interrupt: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.InterruptRequest, _kaguya_pb2.InterruptAck]  # type: ignore[assignment]
    """Unary interrupt: always available, even when no delegation in flight"""
    Telemetry: _aio.UnaryStreamMultiCallable[_kaguya_pb2.TelemetrySubscribe, _kaguya_pb2.TelemetryEvent]  # type: ignore[assignment]
    """Server-streaming telemetry: continuous background context"""

class ReasonerServiceServicer(metaclass=_abc_1.ABCMeta):
    """REASONER SERVICE — Multi-stream design"""

    @_abc_1.abstractmethod
    def Delegate(
        self,
        request_iterator: _MaybeAsyncIterator[_kaguya_pb2.DelegateInput],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_kaguya_pb2.DelegateOutput], _abc.AsyncIterator[_kaguya_pb2.DelegateOutput]]:
        """Bidi per-task: Gateway sends task + context updates, Reasoner streams events"""

    @_abc_1.abstractmethod
    def Interrupt(
        self,
        request: _kaguya_pb2.InterruptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.InterruptAck, _abc.Awaitable[_kaguya_pb2.InterruptAck]]:
        """Unary interrupt: always available, even when no delegation in flight"""

    @_abc_1.abstractmethod
    def Telemetry(
        self,
        request: _kaguya_pb2.TelemetrySubscribe,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_kaguya_pb2.TelemetryEvent], _abc.AsyncIterator[_kaguya_pb2.TelemetryEvent]]:
        """Server-streaming telemetry: continuous background context"""

def add_ReasonerServiceServicer_to_server(servicer: ReasonerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class RouterControlServiceStub:
    """─────────────────────────────────────────────
    GATEWAY CONTROL (Endpoint → Gateway)
    ─────────────────────────────────────────────
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RouterControlServiceAsyncStub: ...
    SendControl: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.ControlSignal, _kaguya_pb2.ControlAck]

@_typing.type_check_only
class RouterControlServiceAsyncStub(RouterControlServiceStub):
    """─────────────────────────────────────────────
    GATEWAY CONTROL (Endpoint → Gateway)
    ─────────────────────────────────────────────
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SendControl: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.ControlSignal, _kaguya_pb2.ControlAck]  # type: ignore[assignment]

class RouterControlServiceServicer(metaclass=_abc_1.ABCMeta):
    """─────────────────────────────────────────────
    GATEWAY CONTROL (Endpoint → Gateway)
    ─────────────────────────────────────────────
    """

    @_abc_1.abstractmethod
    def SendControl(
        self,
        request: _kaguya_pb2.ControlSignal,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.ControlAck, _abc.Awaitable[_kaguya_pb2.ControlAck]]: ...

def add_RouterControlServiceServicer_to_server(servicer: RouterControlServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
