"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import kaguya_pb2 as _kaguya_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ListenerServiceStub:
    """─────────────────────────────────────────────
    LISTENER SERVICE  (Listener → Gateway)
    ─────────────────────────────────────────────
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ListenerServiceAsyncStub: ...
    StreamEvents: _grpc.StreamUnaryMultiCallable[_kaguya_pb2.ListenerEvent, _kaguya_pb2.ListenerAck]

@_typing.type_check_only
class ListenerServiceAsyncStub(ListenerServiceStub):
    """─────────────────────────────────────────────
    LISTENER SERVICE  (Listener → Gateway)
    ─────────────────────────────────────────────
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamEvents: _aio.StreamUnaryMultiCallable[_kaguya_pb2.ListenerEvent, _kaguya_pb2.ListenerAck]  # type: ignore[assignment]

class ListenerServiceServicer(metaclass=_abc_1.ABCMeta):
    """─────────────────────────────────────────────
    LISTENER SERVICE  (Listener → Gateway)
    ─────────────────────────────────────────────
    """

    @_abc_1.abstractmethod
    def StreamEvents(
        self,
        request_iterator: _MaybeAsyncIterator[_kaguya_pb2.ListenerEvent],
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.ListenerAck, _abc.Awaitable[_kaguya_pb2.ListenerAck]]: ...

def add_ListenerServiceServicer_to_server(servicer: ListenerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class TalkerServiceStub:
    """─────────────────────────────────────────────
    TALKER SERVICE  (Gateway → Talker)
    ─────────────────────────────────────────────
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TalkerServiceAsyncStub: ...
    ProcessPrompt: _grpc.UnaryStreamMultiCallable[_kaguya_pb2.TalkerContext, _kaguya_pb2.TalkerOutput]
    Prepare: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.PrepareSignal, _kaguya_pb2.PrepareAck]
    PrefillCache: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.PrefillRequest, _kaguya_pb2.PrefillAck]
    UpdatePersona: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.PersonaConfig, _kaguya_pb2.PersonaAck]

@_typing.type_check_only
class TalkerServiceAsyncStub(TalkerServiceStub):
    """─────────────────────────────────────────────
    TALKER SERVICE  (Gateway → Talker)
    ─────────────────────────────────────────────
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ProcessPrompt: _aio.UnaryStreamMultiCallable[_kaguya_pb2.TalkerContext, _kaguya_pb2.TalkerOutput]  # type: ignore[assignment]
    Prepare: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.PrepareSignal, _kaguya_pb2.PrepareAck]  # type: ignore[assignment]
    PrefillCache: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.PrefillRequest, _kaguya_pb2.PrefillAck]  # type: ignore[assignment]
    UpdatePersona: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.PersonaConfig, _kaguya_pb2.PersonaAck]  # type: ignore[assignment]

class TalkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """─────────────────────────────────────────────
    TALKER SERVICE  (Gateway → Talker)
    ─────────────────────────────────────────────
    """

    @_abc_1.abstractmethod
    def ProcessPrompt(
        self,
        request: _kaguya_pb2.TalkerContext,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_kaguya_pb2.TalkerOutput], _abc.AsyncIterator[_kaguya_pb2.TalkerOutput]]: ...

    @_abc_1.abstractmethod
    def Prepare(
        self,
        request: _kaguya_pb2.PrepareSignal,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.PrepareAck, _abc.Awaitable[_kaguya_pb2.PrepareAck]]: ...

    @_abc_1.abstractmethod
    def PrefillCache(
        self,
        request: _kaguya_pb2.PrefillRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.PrefillAck, _abc.Awaitable[_kaguya_pb2.PrefillAck]]: ...

    @_abc_1.abstractmethod
    def UpdatePersona(
        self,
        request: _kaguya_pb2.PersonaConfig,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.PersonaAck, _abc.Awaitable[_kaguya_pb2.PersonaAck]]: ...

def add_TalkerServiceServicer_to_server(servicer: TalkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class ReasonerServiceStub:
    """─────────────────────────────────────────────
    REASONER SERVICE  (Gateway → Reasoner)
    ─────────────────────────────────────────────
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ReasonerServiceAsyncStub: ...
    ExecuteTask: _grpc.UnaryStreamMultiCallable[_kaguya_pb2.TaskRequest, _kaguya_pb2.ReasonerEvent]
    CancelTask: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.CancelRequest, _kaguya_pb2.CancelAck]

@_typing.type_check_only
class ReasonerServiceAsyncStub(ReasonerServiceStub):
    """─────────────────────────────────────────────
    REASONER SERVICE  (Gateway → Reasoner)
    ─────────────────────────────────────────────
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ExecuteTask: _aio.UnaryStreamMultiCallable[_kaguya_pb2.TaskRequest, _kaguya_pb2.ReasonerEvent]  # type: ignore[assignment]
    CancelTask: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.CancelRequest, _kaguya_pb2.CancelAck]  # type: ignore[assignment]

class ReasonerServiceServicer(metaclass=_abc_1.ABCMeta):
    """─────────────────────────────────────────────
    REASONER SERVICE  (Gateway → Reasoner)
    ─────────────────────────────────────────────
    """

    @_abc_1.abstractmethod
    def ExecuteTask(
        self,
        request: _kaguya_pb2.TaskRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_kaguya_pb2.ReasonerEvent], _abc.AsyncIterator[_kaguya_pb2.ReasonerEvent]]: ...

    @_abc_1.abstractmethod
    def CancelTask(
        self,
        request: _kaguya_pb2.CancelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.CancelAck, _abc.Awaitable[_kaguya_pb2.CancelAck]]: ...

def add_ReasonerServiceServicer_to_server(servicer: ReasonerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class RouterControlServiceStub:
    """─────────────────────────────────────────────
    GATEWAY CONTROL  (Endpoint → Gateway)
    ─────────────────────────────────────────────
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RouterControlServiceAsyncStub: ...
    SendControl: _grpc.UnaryUnaryMultiCallable[_kaguya_pb2.ControlSignal, _kaguya_pb2.ControlAck]

@_typing.type_check_only
class RouterControlServiceAsyncStub(RouterControlServiceStub):
    """─────────────────────────────────────────────
    GATEWAY CONTROL  (Endpoint → Gateway)
    ─────────────────────────────────────────────
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SendControl: _aio.UnaryUnaryMultiCallable[_kaguya_pb2.ControlSignal, _kaguya_pb2.ControlAck]  # type: ignore[assignment]

class RouterControlServiceServicer(metaclass=_abc_1.ABCMeta):
    """─────────────────────────────────────────────
    GATEWAY CONTROL  (Endpoint → Gateway)
    ─────────────────────────────────────────────
    """

    @_abc_1.abstractmethod
    def SendControl(
        self,
        request: _kaguya_pb2.ControlSignal,
        context: _ServicerContext,
    ) -> _typing.Union[_kaguya_pb2.ControlAck, _abc.Awaitable[_kaguya_pb2.ControlAck]]: ...

def add_RouterControlServiceServicer_to_server(servicer: RouterControlServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
