"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Role:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Role.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ROLE_UNSPECIFIED: _Role.ValueType  # 0
    ROLE_SYSTEM: _Role.ValueType  # 1
    ROLE_USER: _Role.ValueType  # 2
    ROLE_ASSISTANT: _Role.ValueType  # 3
    ROLE_TOOL: _Role.ValueType  # 4
    """tool result injection round"""

class Role(_Role, metaclass=_RoleEnumTypeWrapper):
    """─────────────────────────────────────────────
    SHARED TYPES
    ─────────────────────────────────────────────
    """

ROLE_UNSPECIFIED: Role.ValueType  # 0
ROLE_SYSTEM: Role.ValueType  # 1
ROLE_USER: Role.ValueType  # 2
ROLE_ASSISTANT: Role.ValueType  # 3
ROLE_TOOL: Role.ValueType  # 4
"""tool result injection round"""
Global___Role: _TypeAlias = Role  # noqa: Y015

@_typing.final
class ChatMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROLE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    role: Global___Role.ValueType
    content: _builtins.str
    name: _builtins.str
    """tool name when role=ROLE_TOOL"""
    timestamp_ms: _builtins.int
    def __init__(
        self,
        *,
        role: Global___Role.ValueType = ...,
        content: _builtins.str = ...,
        name: _builtins.str = ...,
        timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "name", b"name", "role", b"role", "timestamp_ms", b"timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ChatMessage: _TypeAlias = ChatMessage  # noqa: Y015

@_typing.final
class ToolDefinition(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    ARGS_SCHEMA_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    args_schema: _builtins.str
    """JSON Schema string"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        args_schema: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["args_schema", b"args_schema", "description", b"description", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ToolDefinition: _TypeAlias = ToolDefinition  # noqa: Y015

@_typing.final
class ListenerEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    VAD_SPEECH_START_FIELD_NUMBER: _builtins.int
    VAD_SPEECH_END_FIELD_NUMBER: _builtins.int
    PARTIAL_TRANSCRIPT_FIELD_NUMBER: _builtins.int
    FINAL_TRANSCRIPT_FIELD_NUMBER: _builtins.int
    timestamp_ms: _builtins.int
    @_builtins.property
    def vad_speech_start(self) -> Global___VadSpeechStart: ...
    @_builtins.property
    def vad_speech_end(self) -> Global___VadSpeechEnd: ...
    @_builtins.property
    def partial_transcript(self) -> Global___PartialTranscript: ...
    @_builtins.property
    def final_transcript(self) -> Global___FinalTranscript: ...
    def __init__(
        self,
        *,
        timestamp_ms: _builtins.int = ...,
        vad_speech_start: Global___VadSpeechStart | None = ...,
        vad_speech_end: Global___VadSpeechEnd | None = ...,
        partial_transcript: Global___PartialTranscript | None = ...,
        final_transcript: Global___FinalTranscript | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "final_transcript", b"final_transcript", "partial_transcript", b"partial_transcript", "vad_speech_end", b"vad_speech_end", "vad_speech_start", b"vad_speech_start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "final_transcript", b"final_transcript", "partial_transcript", b"partial_transcript", "timestamp_ms", b"timestamp_ms", "vad_speech_end", b"vad_speech_end", "vad_speech_start", b"vad_speech_start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["vad_speech_start", "vad_speech_end", "partial_transcript", "final_transcript"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___ListenerEvent: _TypeAlias = ListenerEvent  # noqa: Y015

@_typing.final
class VadSpeechStart(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___VadSpeechStart: _TypeAlias = VadSpeechStart  # noqa: Y015

@_typing.final
class VadSpeechEnd(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SILENCE_DURATION_MS_FIELD_NUMBER: _builtins.int
    silence_duration_ms: _builtins.float
    def __init__(
        self,
        *,
        silence_duration_ms: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["silence_duration_ms", b"silence_duration_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VadSpeechEnd: _TypeAlias = VadSpeechEnd  # noqa: Y015

@_typing.final
class PartialTranscript(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PartialTranscript: _TypeAlias = PartialTranscript  # noqa: Y015

@_typing.final
class FinalTranscript(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    CONFIDENCE_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    confidence: _builtins.float
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        confidence: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["confidence", b"confidence", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FinalTranscript: _TypeAlias = FinalTranscript  # noqa: Y015

@_typing.final
class ListenerAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ListenerAck: _TypeAlias = ListenerAck  # noqa: Y015

@_typing.final
class TalkerContext(_message.Message):
    """Full context package assembled by Gateway each turn.
    Gateway assembles; Talker formats. Gateway has no knowledge of prompt format.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CONVERSATION_ID_FIELD_NUMBER: _builtins.int
    TURN_ID_FIELD_NUMBER: _builtins.int
    USER_INPUT_FIELD_NUMBER: _builtins.int
    HISTORY_FIELD_NUMBER: _builtins.int
    MEMORY_CONTENTS_FIELD_NUMBER: _builtins.int
    TOOLS_FIELD_NUMBER: _builtins.int
    ACTIVE_TASKS_JSON_FIELD_NUMBER: _builtins.int
    TOOL_RESULT_CONTENT_FIELD_NUMBER: _builtins.int
    TOOL_REQUEST_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    REASONER_TASK_ID_FIELD_NUMBER: _builtins.int
    REASONER_RESULT_CONTENT_FIELD_NUMBER: _builtins.int
    conversation_id: _builtins.str
    turn_id: _builtins.str
    """unique per ProcessPrompt call"""
    user_input: _builtins.str
    """final_transcript text (natural language)"""
    memory_contents: _builtins.str
    """full MEMORY.md text (natural language → prompt)"""
    active_tasks_json: _builtins.str
    """JSON: ongoing Reasoner task summaries"""
    tool_result_content: _builtins.str
    """natural-language tool result (if tool-result round)"""
    tool_request_id: _builtins.str
    """correlates to ToolRequest.request_id"""
    timestamp_ms: _builtins.int
    reasoner_task_id: _builtins.str
    """correlates to DelegateRequest.task_id"""
    reasoner_result_content: _builtins.str
    """natural-language reasoner result (if reasoner-result round)"""
    @_builtins.property
    def history(self) -> _containers.RepeatedCompositeFieldContainer[Global___ChatMessage]:
        """recent turns, Gateway manages window"""

    @_builtins.property
    def tools(self) -> _containers.RepeatedCompositeFieldContainer[Global___ToolDefinition]: ...
    def __init__(
        self,
        *,
        conversation_id: _builtins.str = ...,
        turn_id: _builtins.str = ...,
        user_input: _builtins.str = ...,
        history: _abc.Iterable[Global___ChatMessage] | None = ...,
        memory_contents: _builtins.str = ...,
        tools: _abc.Iterable[Global___ToolDefinition] | None = ...,
        active_tasks_json: _builtins.str = ...,
        tool_result_content: _builtins.str = ...,
        tool_request_id: _builtins.str = ...,
        timestamp_ms: _builtins.int = ...,
        reasoner_task_id: _builtins.str = ...,
        reasoner_result_content: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_tasks_json", b"active_tasks_json", "conversation_id", b"conversation_id", "history", b"history", "memory_contents", b"memory_contents", "reasoner_result_content", b"reasoner_result_content", "reasoner_task_id", b"reasoner_task_id", "timestamp_ms", b"timestamp_ms", "tool_request_id", b"tool_request_id", "tool_result_content", b"tool_result_content", "tools", b"tools", "turn_id", b"turn_id", "user_input", b"user_input"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TalkerContext: _TypeAlias = TalkerContext  # noqa: Y015

@_typing.final
class TalkerOutput(_message.Message):
    """Streamed back to Gateway during generation.
    One message per sentence boundary or extracted tag.
    seq is monotonically increasing within a single ProcessPrompt call.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SEQ_FIELD_NUMBER: _builtins.int
    RESPONSE_STARTED_FIELD_NUMBER: _builtins.int
    SENTENCE_FIELD_NUMBER: _builtins.int
    EMOTION_FIELD_NUMBER: _builtins.int
    TOOL_REQUEST_FIELD_NUMBER: _builtins.int
    DELEGATE_REQUEST_FIELD_NUMBER: _builtins.int
    RESPONSE_COMPLETE_FIELD_NUMBER: _builtins.int
    seq: _builtins.int
    @_builtins.property
    def response_started(self) -> Global___ResponseStarted: ...
    @_builtins.property
    def sentence(self) -> Global___SentenceEvent: ...
    @_builtins.property
    def emotion(self) -> Global___EmotionEvent: ...
    @_builtins.property
    def tool_request(self) -> Global___ToolRequest: ...
    @_builtins.property
    def delegate_request(self) -> Global___DelegateRequest: ...
    @_builtins.property
    def response_complete(self) -> Global___ResponseComplete: ...
    def __init__(
        self,
        *,
        seq: _builtins.int = ...,
        response_started: Global___ResponseStarted | None = ...,
        sentence: Global___SentenceEvent | None = ...,
        emotion: Global___EmotionEvent | None = ...,
        tool_request: Global___ToolRequest | None = ...,
        delegate_request: Global___DelegateRequest | None = ...,
        response_complete: Global___ResponseComplete | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["delegate_request", b"delegate_request", "emotion", b"emotion", "payload", b"payload", "response_complete", b"response_complete", "response_started", b"response_started", "sentence", b"sentence", "tool_request", b"tool_request"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delegate_request", b"delegate_request", "emotion", b"emotion", "payload", b"payload", "response_complete", b"response_complete", "response_started", b"response_started", "sentence", b"sentence", "seq", b"seq", "tool_request", b"tool_request"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["response_started", "sentence", "emotion", "tool_request", "delegate_request", "response_complete"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___TalkerOutput: _TypeAlias = TalkerOutput  # noqa: Y015

@_typing.final
class ResponseStarted(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TURN_ID_FIELD_NUMBER: _builtins.int
    turn_id: _builtins.str
    def __init__(
        self,
        *,
        turn_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["turn_id", b"turn_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResponseStarted: _TypeAlias = ResponseStarted  # noqa: Y015

@_typing.final
class SentenceEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SentenceEvent: _TypeAlias = SentenceEvent  # noqa: Y015

@_typing.final
class EmotionEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EMOTION_FIELD_NUMBER: _builtins.int
    emotion: _builtins.str
    def __init__(
        self,
        *,
        emotion: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["emotion", b"emotion"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EmotionEvent: _TypeAlias = EmotionEvent  # noqa: Y015

@_typing.final
class ToolRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    TOOL_NAME_FIELD_NUMBER: _builtins.int
    ARGS_JSON_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    """Gateway correlates async result back to this"""
    tool_name: _builtins.str
    args_json: _builtins.str
    """dynamic schema — string (not Struct) for simplicity"""
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        tool_name: _builtins.str = ...,
        args_json: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["args_json", b"args_json", "request_id", b"request_id", "tool_name", b"tool_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ToolRequest: _TypeAlias = ToolRequest  # noqa: Y015

@_typing.final
class DelegateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """generated by Talker; stable through full Reasoner lifecycle"""
    description: _builtins.str
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DelegateRequest: _TypeAlias = DelegateRequest  # noqa: Y015

@_typing.final
class ResponseComplete(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TURN_ID_FIELD_NUMBER: _builtins.int
    WAS_INTERRUPTED_FIELD_NUMBER: _builtins.int
    turn_id: _builtins.str
    was_interrupted: _builtins.bool
    def __init__(
        self,
        *,
        turn_id: _builtins.str = ...,
        was_interrupted: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["turn_id", b"turn_id", "was_interrupted", b"was_interrupted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResponseComplete: _TypeAlias = ResponseComplete  # noqa: Y015

@_typing.final
class PrepareSignal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONVERSATION_ID_FIELD_NUMBER: _builtins.int
    conversation_id: _builtins.str
    def __init__(
        self,
        *,
        conversation_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conversation_id", b"conversation_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrepareSignal: _TypeAlias = PrepareSignal  # noqa: Y015

@_typing.final
class PrepareAck(_message.Message):
    """spoken_text and unspoken_text are both empty if Talker was already idle."""

    DESCRIPTOR: _descriptor.Descriptor

    SPOKEN_TEXT_FIELD_NUMBER: _builtins.int
    UNSPOKEN_TEXT_FIELD_NUMBER: _builtins.int
    spoken_text: _builtins.str
    unspoken_text: _builtins.str
    def __init__(
        self,
        *,
        spoken_text: _builtins.str = ...,
        unspoken_text: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["spoken_text", b"spoken_text", "unspoken_text", b"unspoken_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrepareAck: _TypeAlias = PrepareAck  # noqa: Y015

@_typing.final
class PrefillRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONVERSATION_ID_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    conversation_id: _builtins.str
    @_builtins.property
    def context(self) -> Global___TalkerContext:
        """same shape; n_predict=0 implied by call type"""

    def __init__(
        self,
        *,
        conversation_id: _builtins.str = ...,
        context: Global___TalkerContext | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "conversation_id", b"conversation_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrefillRequest: _TypeAlias = PrefillRequest  # noqa: Y015

@_typing.final
class PrefillAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___PrefillAck: _TypeAlias = PrefillAck  # noqa: Y015

@_typing.final
class PersonaConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOUL_MD_FIELD_NUMBER: _builtins.int
    IDENTITY_MD_FIELD_NUMBER: _builtins.int
    MEMORY_MD_FIELD_NUMBER: _builtins.int
    soul_md: _builtins.str
    identity_md: _builtins.str
    memory_md: _builtins.str
    def __init__(
        self,
        *,
        soul_md: _builtins.str = ...,
        identity_md: _builtins.str = ...,
        memory_md: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identity_md", b"identity_md", "memory_md", b"memory_md", "soul_md", b"soul_md"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PersonaConfig: _TypeAlias = PersonaConfig  # noqa: Y015

@_typing.final
class PersonaAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___PersonaAck: _TypeAlias = PersonaAck  # noqa: Y015

@_typing.final
class TaskRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TASK_ID_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """same ID from DelegateRequest.task_id"""
    description: _builtins.str
    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        description: _builtins.str = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "metadata", b"metadata", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskRequest: _TypeAlias = TaskRequest  # noqa: Y015

@_typing.final
class ReasonerEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    STARTED_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    COMPLETED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    timestamp_ms: _builtins.int
    @_builtins.property
    def started(self) -> Global___ReasonerStarted: ...
    @_builtins.property
    def step(self) -> Global___ReasonerIntermediateStep: ...
    @_builtins.property
    def output(self) -> Global___ReasonerOutput: ...
    @_builtins.property
    def completed(self) -> Global___ReasonerCompleted: ...
    @_builtins.property
    def error(self) -> Global___ReasonerError: ...
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        timestamp_ms: _builtins.int = ...,
        started: Global___ReasonerStarted | None = ...,
        step: Global___ReasonerIntermediateStep | None = ...,
        output: Global___ReasonerOutput | None = ...,
        completed: Global___ReasonerCompleted | None = ...,
        error: Global___ReasonerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["completed", b"completed", "error", b"error", "event", b"event", "output", b"output", "started", b"started", "step", b"step"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completed", b"completed", "error", b"error", "event", b"event", "output", b"output", "started", b"started", "step", b"step", "task_id", b"task_id", "timestamp_ms", b"timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["started", "step", "output", "completed", "error"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___ReasonerEvent: _TypeAlias = ReasonerEvent  # noqa: Y015

@_typing.final
class ReasonerStarted(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FRAMEWORK_FIELD_NUMBER: _builtins.int
    framework: _builtins.str
    def __init__(
        self,
        *,
        framework: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["framework", b"framework"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReasonerStarted: _TypeAlias = ReasonerStarted  # noqa: Y015

@_typing.final
class ReasonerIntermediateStep(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    def __init__(
        self,
        *,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReasonerIntermediateStep: _TypeAlias = ReasonerIntermediateStep  # noqa: Y015

@_typing.final
class ReasonerOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    content: _builtins.str
    def __init__(
        self,
        *,
        content: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReasonerOutput: _TypeAlias = ReasonerOutput  # noqa: Y015

@_typing.final
class ReasonerCompleted(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUMMARY_FIELD_NUMBER: _builtins.int
    summary: _builtins.str
    def __init__(
        self,
        *,
        summary: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReasonerCompleted: _TypeAlias = ReasonerCompleted  # noqa: Y015

@_typing.final
class ReasonerError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    code: _builtins.int
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
        code: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReasonerError: _TypeAlias = ReasonerError  # noqa: Y015

@_typing.final
class CancelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CancelRequest: _TypeAlias = CancelRequest  # noqa: Y015

@_typing.final
class CancelAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CancelAck: _TypeAlias = CancelAck  # noqa: Y015

@_typing.final
class ControlSignal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STOP_FIELD_NUMBER: _builtins.int
    APPROVAL_FIELD_NUMBER: _builtins.int
    SHUTDOWN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stop(self) -> Global___StopSignal: ...
    @_builtins.property
    def approval(self) -> Global___ApprovalSignal: ...
    @_builtins.property
    def shutdown(self) -> Global___ShutdownSignal: ...
    def __init__(
        self,
        *,
        stop: Global___StopSignal | None = ...,
        approval: Global___ApprovalSignal | None = ...,
        shutdown: Global___ShutdownSignal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["approval", b"approval", "shutdown", b"shutdown", "signal", b"signal", "stop", b"stop"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approval", b"approval", "shutdown", b"shutdown", "signal", b"signal", "stop", b"stop"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_signal: _TypeAlias = _typing.Literal["stop", "approval", "shutdown"]  # noqa: Y015
    _WhichOneofArgType_signal: _TypeAlias = _typing.Literal["signal", b"signal"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_signal) -> _WhichOneofReturnType_signal | None: ...

Global___ControlSignal: _TypeAlias = ControlSignal  # noqa: Y015

@_typing.final
class StopSignal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StopSignal: _TypeAlias = StopSignal  # noqa: Y015

@_typing.final
class ApprovalSignal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: _builtins.int
    context: _builtins.str
    def __init__(
        self,
        *,
        context: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApprovalSignal: _TypeAlias = ApprovalSignal  # noqa: Y015

@_typing.final
class ShutdownSignal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ShutdownSignal: _TypeAlias = ShutdownSignal  # noqa: Y015

@_typing.final
class ControlAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ControlAck: _TypeAlias = ControlAck  # noqa: Y015
