# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kaguya_pb2 as kaguya__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kaguya_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ListenerServiceStub(object):
    """─────────────────────────────────────────────
    LISTENER SERVICE  (Listener → Gateway)
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.stream_unary(
                '/kaguya.v1.ListenerService/StreamEvents',
                request_serializer=kaguya__pb2.ListenerEvent.SerializeToString,
                response_deserializer=kaguya__pb2.ListenerAck.FromString,
                _registered_method=True)


class ListenerServiceServicer(object):
    """─────────────────────────────────────────────
    LISTENER SERVICE  (Listener → Gateway)
    ─────────────────────────────────────────────

    """

    def StreamEvents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListenerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=kaguya__pb2.ListenerEvent.FromString,
                    response_serializer=kaguya__pb2.ListenerAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.ListenerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.ListenerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListenerService(object):
    """─────────────────────────────────────────────
    LISTENER SERVICE  (Listener → Gateway)
    ─────────────────────────────────────────────

    """

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kaguya.v1.ListenerService/StreamEvents',
            kaguya__pb2.ListenerEvent.SerializeToString,
            kaguya__pb2.ListenerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TalkerServiceStub(object):
    """─────────────────────────────────────────────
    TALKER SERVICE  (Gateway → Talker)
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPrompt = channel.unary_stream(
                '/kaguya.v1.TalkerService/ProcessPrompt',
                request_serializer=kaguya__pb2.TalkerContext.SerializeToString,
                response_deserializer=kaguya__pb2.TalkerOutput.FromString,
                _registered_method=True)
        self.Prepare = channel.unary_unary(
                '/kaguya.v1.TalkerService/Prepare',
                request_serializer=kaguya__pb2.PrepareSignal.SerializeToString,
                response_deserializer=kaguya__pb2.PrepareAck.FromString,
                _registered_method=True)
        self.PrefillCache = channel.unary_unary(
                '/kaguya.v1.TalkerService/PrefillCache',
                request_serializer=kaguya__pb2.PrefillRequest.SerializeToString,
                response_deserializer=kaguya__pb2.PrefillAck.FromString,
                _registered_method=True)
        self.UpdatePersona = channel.unary_unary(
                '/kaguya.v1.TalkerService/UpdatePersona',
                request_serializer=kaguya__pb2.PersonaConfig.SerializeToString,
                response_deserializer=kaguya__pb2.PersonaAck.FromString,
                _registered_method=True)


class TalkerServiceServicer(object):
    """─────────────────────────────────────────────
    TALKER SERVICE  (Gateway → Talker)
    ─────────────────────────────────────────────

    """

    def ProcessPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrefillCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePersona(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TalkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPrompt': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessPrompt,
                    request_deserializer=kaguya__pb2.TalkerContext.FromString,
                    response_serializer=kaguya__pb2.TalkerOutput.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=kaguya__pb2.PrepareSignal.FromString,
                    response_serializer=kaguya__pb2.PrepareAck.SerializeToString,
            ),
            'PrefillCache': grpc.unary_unary_rpc_method_handler(
                    servicer.PrefillCache,
                    request_deserializer=kaguya__pb2.PrefillRequest.FromString,
                    response_serializer=kaguya__pb2.PrefillAck.SerializeToString,
            ),
            'UpdatePersona': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePersona,
                    request_deserializer=kaguya__pb2.PersonaConfig.FromString,
                    response_serializer=kaguya__pb2.PersonaAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.TalkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.TalkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TalkerService(object):
    """─────────────────────────────────────────────
    TALKER SERVICE  (Gateway → Talker)
    ─────────────────────────────────────────────

    """

    @staticmethod
    def ProcessPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kaguya.v1.TalkerService/ProcessPrompt',
            kaguya__pb2.TalkerContext.SerializeToString,
            kaguya__pb2.TalkerOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.TalkerService/Prepare',
            kaguya__pb2.PrepareSignal.SerializeToString,
            kaguya__pb2.PrepareAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrefillCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.TalkerService/PrefillCache',
            kaguya__pb2.PrefillRequest.SerializeToString,
            kaguya__pb2.PrefillAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.TalkerService/UpdatePersona',
            kaguya__pb2.PersonaConfig.SerializeToString,
            kaguya__pb2.PersonaAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReasonerServiceStub(object):
    """─────────────────────────────────────────────
    REASONER SERVICE  (Gateway → Reasoner)
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_stream(
                '/kaguya.v1.ReasonerService/ExecuteTask',
                request_serializer=kaguya__pb2.TaskRequest.SerializeToString,
                response_deserializer=kaguya__pb2.ReasonerEvent.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/kaguya.v1.ReasonerService/CancelTask',
                request_serializer=kaguya__pb2.CancelRequest.SerializeToString,
                response_deserializer=kaguya__pb2.CancelAck.FromString,
                _registered_method=True)


class ReasonerServiceServicer(object):
    """─────────────────────────────────────────────
    REASONER SERVICE  (Gateway → Reasoner)
    ─────────────────────────────────────────────

    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReasonerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=kaguya__pb2.TaskRequest.FromString,
                    response_serializer=kaguya__pb2.ReasonerEvent.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=kaguya__pb2.CancelRequest.FromString,
                    response_serializer=kaguya__pb2.CancelAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.ReasonerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.ReasonerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReasonerService(object):
    """─────────────────────────────────────────────
    REASONER SERVICE  (Gateway → Reasoner)
    ─────────────────────────────────────────────

    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kaguya.v1.ReasonerService/ExecuteTask',
            kaguya__pb2.TaskRequest.SerializeToString,
            kaguya__pb2.ReasonerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.ReasonerService/CancelTask',
            kaguya__pb2.CancelRequest.SerializeToString,
            kaguya__pb2.CancelAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RouterControlServiceStub(object):
    """─────────────────────────────────────────────
    GATEWAY CONTROL  (Endpoint → Gateway)
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendControl = channel.unary_unary(
                '/kaguya.v1.RouterControlService/SendControl',
                request_serializer=kaguya__pb2.ControlSignal.SerializeToString,
                response_deserializer=kaguya__pb2.ControlAck.FromString,
                _registered_method=True)


class RouterControlServiceServicer(object):
    """─────────────────────────────────────────────
    GATEWAY CONTROL  (Endpoint → Gateway)
    ─────────────────────────────────────────────

    """

    def SendControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControl,
                    request_deserializer=kaguya__pb2.ControlSignal.FromString,
                    response_serializer=kaguya__pb2.ControlAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaguya.v1.RouterControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kaguya.v1.RouterControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterControlService(object):
    """─────────────────────────────────────────────
    GATEWAY CONTROL  (Endpoint → Gateway)
    ─────────────────────────────────────────────

    """

    @staticmethod
    def SendControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kaguya.v1.RouterControlService/SendControl',
            kaguya__pb2.ControlSignal.SerializeToString,
            kaguya__pb2.ControlAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
