name: Proto Lint

on: [push, pull_request]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - run: buf lint proto/
      - run: buf breaking proto/ --against '.git#branch=main'
